### PR TITLE
draft of FP301

### PR DESCRIPTION
**Pull request by mcgoodman**
Here's a draft of FP301. It contains instructions for documenting code using Roxygen2 and for writing READMEs based on the rrtools template. There's an image referenced by FP301.md as well.

### CODE REVIEW

**Review by FlukeAndFeather — CHANGES_REQUESTED** [review]
Thanks Maurice! This is great but large chunks are redundant with [DOC102](https://github.com/FlukeAndFeather/jese4sci-DOC/blob/master/DOC102.md) and [DOC201](https://github.com/FlukeAndFeather/jese4sci-DOC/blob/master/DOC201.md). Can you refer students to those lessons instead?

**Comment by mcgoodman** [comment]
Could you provide more specific suggestions? The issue you opened (#5 ) says: 

> "Document objects". Roxygen comments for all functions in R/ and objects in data/. Fill out rrtools README.Rmd template.

It seems that [DOC102](https://github.com/FlukeAndFeather/jese4sci-DOC/blob/master/DOC102.md) does not provide instructions for filling out the rrtools README, so the material here doesn't entirely overlap with DOC102. Would you like me to substitute just the part where I describe a README, or the whole section?

As for Roxygen comments, referring students to [DOC201](https://github.com/FlukeAndFeather/jese4sci-DOC/blob/master/DOC201.md) seemingly requires extra work of students who did not choose to complete the DOC path. Should I instead refer them to the relevant resources you have listed under "How to use roxygen" in the DOC201 instructions?

**Comment by FlukeAndFeather** [comment]
I see what you mean. However, for the FP track, I want to keep the instructions brief and trust students to figure it out/ask questions. The purpose of the final project is to apply techniques/concepts they learned in week 1 with less guidance. So my preference is to err on the side of fewer instructions and more iterative feedback, rather than more info up front.

If no one in the project group completed DOC201, then I think I want to either have one student in the group take that lesson in week 2 or have the group skip this step entirely. There's more material in this course than everyone will get through, so I'm ok with them skipping some parts of the final project. Better to learn fewer things thoroughly than more things quickly.

**Comment by mcgoodman** [comment]
Substituted the instructions from your other modules in!

**Review by FlukeAndFeather — APPROVED** [review]
Great, thanks! Sorry to make you erase all that content.

**Pull request merged**
